version: 2.1

jobs:
  build-and-test-extension:
    docker:
      - image: circleci/node:latest-browsers

    environment:
      # CircleCI builds production builds and thus uses production environment variables
      SENTRY_DSN: https://fbd070810c8c47f1bf9a1a17e8909d4d@sentry.prod.mozaws.net/524
      TELEMETRY_SERVER: https://incoming.telemetry.mozilla.org

    working_directory: ~/checkout

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Output the current Sentry configuration
          command: npx sentry-cli info

      - run:
          name: Build extension - Firefox
          command: yarn build:production

      - run:
          name: Build extension - Chrome
          command: TARGET_BROWSER=chrome yarn build:production

      - store_artifacts:
          path: "dist"
          destination: "dist"

      - run:
          name: Run unit tests
          command: yarn test

      - store_artifacts:
          path: "test/results"
          destination: "test/results"

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test-extension
