version: 2.1

jobs:
  build-and-test-extension:
    docker:
      - image: circleci/node:latest-browsers

    working_directory: ~/checkout

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Use CI non-sensitive env vars
          command: cp .env.ci .env.production

      - run:
          name: Use CI non-sensitive env vars for testing
          command: cp .env.ci .env.development

      - run:
          name: Output the current Sentry configuration
          command: npx sentry-cli info || true

      - run:
          name: Build extension - Firefox
          command: yarn build:production

      - run:
          name: Build extension - Chrome
          command: TARGET_BROWSER=chrome yarn build:production

      - store_artifacts:
          path: "dist"
          destination: "dist"

      - run:
          name: Run unit tests
          command: yarn test

      - store_artifacts:
          path: "test/results"
          destination: "test/results"

workflows:
  version: 2
  ci:
    jobs:
      - build-and-test-extension
